# Generated by Django 2.2.3 on 2019-07-13 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchDepartment', '0002_auto_20190710_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='AdministrativeDistrict',
            field=models.CharField(max_length=17),
        ),
        migrations.AlterField(
            model_name='request',
            name='TypeOfDefect',
            field=models.CharField(max_length=68),
        ),
    ]
